title: Promise对象--笔记
date: 2017-02-18 14:34:31
tags: [ES6, 笔记]
---

#### Promise含义

确保在将来发生的事情之后执行，异步操作有`Pending`,`Resolved`,`Rejected`三种状态，只有第一种，到后面两种状态行为。

#### 基本用法

```js
var promise = new Promise(function(resolve, reject) {
  // ... some code
  if (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});
```

<!-- more -->

```js
promise.then(function(value) {
  // success
}, function(error) {
  // failure
});
```

* 异步加载图片实例

```js
function loadImageAsync(url) {
  return new Promise(function(resolve, reject) {
    var image = new Image();
    image.onload = function() {
      resolve(image);
    };
    image.onerror = function() {
      reject(new Error('Could not load image at ' + url));
    };
    image.src = url;
  });
}
```

#### Promise.prototype.then()

实例方法，第一个参数，成功回调函数；第二个参数，失败回调。

可以链式调用，第一次`then`函数返回作为后一次`then`调用的参数。

```js
getJSON("/post/1.json").then(
  post => getJSON(post.commentURL)
).then(
  comments => console.log("Resolved: ", comments),
  err => console.log("Rejected: ", err)
);
```

#### Promise.prototype.catch()

发生错误时，捕获的异常的回调

```js
getJSON("/posts.json").then(function(posts) {
  // ...
}).catch(function(error) {
  // 处理 getJSON 和 前一个回调函数运行时发生的错误
  console.log('发生错误！', error);
});
```

异步过程出错状态会成`Reject`或`then`回调函数报错，都会被`catch`捕获。所以尽量不要在`then`里定义reject回调方法，而是在`catch`里处理

#### Promise.all()

* 将多个Promise实例包装一个新的`var p = Promise.all([p1, p2, p3]);`，`p1,p2,p3`都是Promise实例，如果不是会先调用`Promise.resolve`方法。

* 返回结果，所有都`fulfilled`才返回`p1,p2,p3`返回值组成的数组；只要有一个状态是`rejected`的，就会返回第一个`reject`实例的值。

#### Promise.arce()

* 使用方法同`all()`，`var p = Promise.race([p1, p2, p3]);`，但是返回结果，只要`p1,p2,p3`有一个率先状态返回，就会直接传递给`p`的回调函数

#### Promise.resolve()

需要时候将现有对象转为`Promise`对象：

```js
Promise.resolve('foo')
// 等价于
new Promise(resolve => resolve('foo'))
```

* 参数是`Promise`对象，则不修改

* 参数是一个具有`then`方法的对象，则转成`Promise`对象后，立即执行`then`方法

* 参数不是对象，转成`Promise`对象后，状态为`Resolved`

* 不带参数，直接返回一个`Resolved`状态的`Promise`对象

```js
setTimeout(function () {
  console.log('three');
}, 0);
Promise.resolve().then(function () {
  console.log('two');
});
console.log('one');
// one
// two
// three
```

`promise`是在本轮“事件循环”结束时调用，而`setTimeout`是下一轮“事件循环”

#### Promise.reject()

* 返回`Promise`实例，状态为`rejected`，参数为`reject`的理由

#### 附加方法

* `done`，总在`Promse`回调链尾部使用，它内部调用的是`then`，只是在尾部会捕捉到任何可能出现的错误，并全局抛出

* `finally`，不管`promise`状态如何最后都会执行的处理，一般用于关闭资源处理

#### 应用

* 加载图片

```js
const preloadImage = function (path) {
  return new Promise(function (resolve, reject) {
    var image = new Image();
    image.onload  = resolve;
    image.onerror = reject;
    image.src = path;
  });
};
```

* Generator函数与Promise的结合(流程管理)

```js
function getFoo () {
  return new Promise(function (resolve, reject){
    resolve('foo');
  });
}
var g = function* () {
  try {
    var foo = yield getFoo();
    console.log(foo);
  } catch (e) {
    console.log(e);
  }
};
function run (generator) {
  var it = generator();
  function go(result) {
    if (result.done) return result.value;
    return result.value.then(function (value) {
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(error));
    });
  }

  go(it.next());
}
run(g);
```

#### Promise.try()

```js
const f = () => console.log('now');
Promise.resolve().then(f);
console.log('next');
// next
// now
```

以上同步方法，使用异异步处理，如下2中方法：

* `async`函数，`async`方法的异常需要用`catch`捕获

```js
const f = () => console.log('now');
(async () => f())()
.then(...)
.catch(...)
```

* `promise`

```js
const f = () => console.log('now');
(
  () => new Promise(
    resolve => resolve(f())
  )
)();
console.log('next');
```

* 为处理如上的需求，提案`Promise,try()`方法代替

```js
const f = () => console.log('now');
Promise.try(f);
console.log('next');
// now
// next
```

在其他库`Bluebird`,`Q`,`when`已经提供该方法